=== AdamFoster/Android-Fingering-Chart/res/xml/instrument.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.adamfoster.net/instrument" elementFormDefault="qualified" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ins="http://www.adamfoster.net/instrument"
    xmlns:android="http://schemas.android.com/apk/res/android" >

    <xsd:element name="key" type="xsd:string" />
    <xsd:element name="instrument" type="ins:instrument" />

    <xsd:complexType name="keys">
    	<xsd:sequence>
    		<xsd:element ref="ins:key" maxOccurs="unbounded" minOccurs="0"/>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="baseKey">
        <xsd:attribute name="name" type="xsd:string" />
        <xsd:attribute name="positionx" type="xsd:string" />
        <xsd:attribute name="positiony" type="xsd:string" />
        <xsd:attribute name="type" type="xsd:string" />
        <xsd:attribute name="radius" type="xsd:string" use="optional" />
        <xsd:attribute name="width" type="xsd:string" use="optional" />
        <xsd:attribute name="height" type="xsd:string" use="optional" />
    </xsd:complexType>
    
    <xsd:complexType name="baseKeys">
        <xsd:sequence>
            <xsd:element name="baseKey" type="ins:baseKey" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="fingering">
        <!-- xsd:sequence>
            <xsd:element name="keysDown" type="ins:keys" minOccurs="0" maxOccurs="1" />
            <xsd:element name="ringsDown" type="ins:keys" minOccurs="0" maxOccurs="1" />
            <xsd:element name="keysHalfDown" type="ins:keys" minOccurs="0" maxOccurs="1" />
            <xsd:element name="keysTrillDown" type="ins:keys" minOccurs="0" maxOccurs="1" />
            <xsd:element name="keysHalfTrillDown" type="ins:keys" minOccurs="0" maxOccurs="1" />
            <xsd:element name="ringsTrillDown" type="ins:keys" minOccurs="0" maxOccurs="1" />
            <xsd:element name="keysTrillUp" type="ins:keys" minOccurs="0" maxOccurs="1" />
            <xsd:element name="keysHalfTrillUp" type="ins:keys" minOccurs="0" maxOccurs="1" />
            <xsd:element name="ringsTrillUp" type="ins:keys" minOccurs="0" maxOccurs="1" />
        </xsd:sequence>  -->
        <xsd:attribute name="name" type="xsd:string" />
        <xsd:attribute name="comment" type="xsd:string" />
        <xsd:attribute name="keysDown" type="xsd:string" use="optional" />
        <xsd:attribute name="keysHalfDown" type="xsd:string" use="optional" />
        <xsd:attribute name="keysTrillDown" type="xsd:string" use="optional" />
        <xsd:attribute name="keysTrillUp" type="xsd:string" use="optional" />
        <xsd:attribute name="ringsDown" type="xsd:string" use="optional" />
        <xsd:attribute name="ringsTrillDown" type="xsd:string" use="optional" />
        <xsd:attribute name="ringsTrillUp" type="xsd:string" use="optional" />
    </xsd:complexType>
    
    <xsd:complexType name="note">
        <xsd:sequence>    
            <xsd:element name="fingering" type="ins:fingering" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" />
    </xsd:complexType>
    
    <xsd:complexType name="set">
        <xsd:sequence>
            <xsd:element name="note" type="ins:note" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" />
    </xsd:complexType>
    
    <xsd:complexType name="instrument">
        <xsd:sequence>
            <xsd:element name="baseKeys" type="ins:baseKeys" minOccurs="1" maxOccurs="1" />
            <xsd:element name="set" type="ins:set" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" />
        <xsd:attribute name="image" type="xsd:string" />
    </xsd:complexType>
    
</xsd:schema>

=== AdamFoster/Android-Fingering-Chart/res/xml/clarinet.xml
<?xml version="1.0" encoding="UTF-8"?>
<ins:instrument xmlns:ins="http://www.adamfoster.net/instrument" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.adamfoster.net/instrument instrument.xsd "
    name="Clarinet" image="@drawable/clarinet" >
  <ins:baseKeys>
    <!-- Left Hand -->
    <ins:baseKey name="R" positionx="0.280" positiony="0.200" width="0.008" height="0.014" type="oval" />
    <ins:baseKey name="T" positionx="0.280" positiony="0.230" radius="0.01" type="circle" />
    <ins:baseKey name="L-A" positionx="0.477" positiony="0.252" width="0.011" height="0.015" type="oval" />
    <ins:baseKey name="L-G#" positionx="0.580" positiony="0.251" width="0.014" height="0.02" type="rectangle" />
    <ins:baseKey name="L-1" positionx="0.466" positiony="0.290" radius="0.012" type="circle" />
    <ins:baseKey name="L-2" positionx="0.475" positiony="0.360" radius="0.012" type="circle" />
    <ins:baseKey name="L-Eb" positionx="0.440" positiony="0.383" width="0.03" height="0.01" type="rectangle" />
    <ins:baseKey name="L-3" positionx="0.488" positiony="0.411" radius="0.012" type="circle" />
    <ins:baseKey name="L-C#" positionx="0.540" positiony="0.424" width="0.02" height="0.012" type="rectangle" />
    <ins:baseKey name="L-F" positionx="0.624" positiony="0.442" width="0.015" height="0.01" type="rectangle" />
    <ins:baseKey name="L-F#" positionx="0.687" positiony="0.468" width="0.01" height="0.02" type="rectangle" />
    <ins:baseKey name="L-E" positionx="0.609" positiony="0.475" width="0.015" height="0.015" type="rectangle" />
    <ins:baseKey name="L2-G#" positionx="0.645" positiony="0.519" radius="0.006" type="circle" />
    
    <!-- Right hand -->
    <ins:baseKey name="RT-1" positionx="0.248" positiony="0.428" width="0.009" height="0.006" type="oval" />
    <ins:baseKey name="RT-2" positionx="0.248" positiony="0.450" width="0.009" height="0.006" type="oval" />
    <ins:baseKey name="RT-3" positionx="0.270" positiony="0.466" width="0.009" height="0.006" type="oval" />
    <ins:baseKey name="RT-4" positionx="0.270" positiony="0.487" width="0.009" height="0.006" type="oval" />
    <ins:baseKey name="R-1" positionx="0.486" positiony="0.537" radius="0.014" type="circle" />
    <ins:baseKey name="R-2" positionx="0.489" positiony="0.592" radius="0.014" type="circle" />
    <ins:baseKey name="R-B" positionx="0.405" positiony="0.612" width="0.025" height="0.01" type="rectangle" />
    <ins:baseKey name="R-3" positionx="0.489" positiony="0.643" radius="0.014" type="circle" />
    <ins:baseKey name="R-F#" positionx="0.270" positiony="0.670" radius="0.007" type="circle" />
    <ins:baseKey name="R-G#" positionx="0.340" positiony="0.680" height="0.007" width="0.013" angle="20.0" type="oval" />
    <ins:baseKey name="R-E" positionx="0.250" positiony="0.690" radius="0.007" type="circle" />
    <ins:baseKey name="R-F" positionx="0.320" positiony="0.700" height="0.007" width="0.013" angle="20.0" type="oval" />
    
    
  </ins:baseKeys>
  <ins:set name="Notes">

    <!-- Chalumeau Register: E3 to B4 -->
    <ins:note name="E3 / Fb3">
      <ins:fingering name="Left" comment="Use in combination with fingerings using right little finger or no little fingers" keysDown="T,L-1,L-2,L-3,L-E,R-1,R-2,R-3"/>
      <ins:fingering name="Right" comment="Use in combination with fingerings using left little finger or no little fingers" keysDown="T,L-1,L-2,L-3,R-1,R-2,R-3,R-E"/>
      <ins:fingering name="F3/C5" comment="Use in combination with F3 or C5" keysDown="T,L-1,L-2,L-3,L-E,R-1,R-2,R-3,R-F"/>
    </ins:note>
    <ins:note name="E#3 / F3">
      <ins:fingering name="Left" comment="Use in combination with fingerings using right little finger or no little fingers" keysDown="T,L-1,L-2,L-3,L-F,R-1,R-2,R-3"/>
      <ins:fingering name="Right" comment="Use in combination with fingerings using left little finger or no little fingers" keysDown="T,L-1,L-2,L-3,R-1,R-2,R-3,R-F"/>
    </ins:note>
    <ins:note name="F#3 / Gb3">
      <ins:fingering name="Left" comment="Use in combination with fingerings using right little finger or no little fingers" keysDown="T,L-1,L-2,L-3,L-F#,R-1,R-2,R-3"/>
      <ins:fingering name="Right" comment="Use in combination with fingerings using left little finger or no little fingers" keysDown="T,L-1,L-2,L-3,R-1,R-2,R-3,R-F#"/>
      <ins:fingering name="F3/C5" comment="Use in combination with F3 or C5" keysDown="T,L-1,L-2,L-3,L-F#,R-1,R-2,R-3,R-F"/>
    </ins:note>
    <ins:note name="G3">
      <ins:fingering name="Basic" comment="Basic" keysDown="T,L-1,L-2,L-3,R-1,R-2,R-3"/>
    </ins:note>
    <ins:note name="G#3 / Ab3">
      <ins:fingering name="Basic" comment="Basic" keysDown="T,L-1,L-2,L-3,R-1,R-2,R-3,R-G#"/>
      <ins:fingering name="LH-G" comment="For models with LH G#-key, use in combination with fingerings using right little finger or no little fingers." keysDown="T,L-1,L-2,L-3,L2-G#,R-1,R-2,R-3"/>
    </ins:note>
    <ins:note name="A3">
      <ins:fingering name="Basic" comment="Basic" keysDown="T,L-1,L-2,L-3,R-1,R-2"/>
    </ins:note>
    <ins:note name="A#3 / Bb3">
      <ins:fingering name="Basic" comment="Basic" keysDown="T,L-1,L-2,L-3,R-1"/>
    </ins:note>
    <ins:note name="B3 / Cb4">
      <ins:fingering name="Basic" comment="Basic" keysDown="T,L-1,L-2,L-3,R-2"/>
      <ins:fingering name="Basic" comment="Chromatic, use in combination with Bb3 or F4" keysDown="T,L-1,L-2,L-3,R-1,R-B"/>
    </ins:note>
    <ins:note name="B#3 / C4">
      <ins:fingering name="Basic" comment="Basic" keysDown="T,L-1,L-2,L-3"/>
    </ins:note>
    <ins:note name="C#4 / Db4">
      <ins:fingering name="Basic" comment="Basic" keysDown="T,L-1,L-2,L-3,L-C#"/>
    </ins:note>
    <ins:note name="D4">
      <ins:fingering name="Basic" comment="Basic" keysDown="T,L-1,L-2"/>
    </ins:note>
    <ins:note name="D#4 / Eb4">
      <ins:fingering name="Basic" comment="Basic" keysDown="T,L-1,L-2,RT-4"/>
      <ins:fingering name="Chromatic" comment="Chromatic and trill fingering, use in combination with D4 and A5" keysDown="T,L-1,L-2,L-Eb"/>
      <ins:fingering name="RH1" comment="Sharp, use for facility in combination with fingerings involving RH 1" keysDown="T,L-1,R-1"/>
      <ins:fingering name="RH2" comment="Sharp, use for facility in combination with fingerings involving RH 2" keysDown="T,L-1,R-2"/>
      <ins:fingering name="7-Ring" comment="For 7-ring models, use in combination with C4" keysDown="T,L-1,L-3"/>
    </ins:note>
    <ins:note name="E4 / Fb4">
      <ins:fingering name="Basic" comment="Basic" keysDown="T,L-1"/>
      <ins:fingering name="Rounnd" comment="Rounder and lower in pitch than basic fingering" keysDown="T,L-1,L-Eb,RT-4,R-3,R-F"/>
      <ins:fingering name="Long" comment="Produces louder, clear sound, especially useful for long notes" keysDown="T,L-1,L-Eb,L-C#,RT-4,R-1,R-2,R-3,R-F"/>
    </ins:note>
    <ins:note name="E#4 / F4">
      <ins:fingering name="Basic" comment="Basic" keysDown="T"/>
    </ins:note>
    <ins:note name="F#4 / Gb4">
      <ins:fingering name="Basic" comment="Try using RH-1,2,3 in different conbinations for better intonation and tone" keysDown="L-1"/>
      <ins:fingering name="Chromatic" comment="Chromatic, use in combination with F4. Try using RH-1,2,3 in different conbinations for better intonation and tone" keysDown="T,RT-3,RT-4"/>
    </ins:note>
    <ins:note name="G4">
      <ins:fingering name="Basic" comment="Basic. Try using RH-1,2,3 in different conbinations for better intonation and tone" keysDown=""/>
    </ins:note>
    <ins:note name="G#4 / Ab4">
      <ins:fingering name="Basic" comment="Basic. Try different RH combinations for better intonation and tone" keysDown="L-G#"/>
      <ins:fingering name="F4" comment="Use in combination with F4. Try different RH combinations for better intonation and tone" keysDown="T,L-G#,RT-3,RT-4"/>
      <ins:fingering name="Flat" comment="Flatter" keysDown="L-G#,L-2,L-3,RT-4,R-1"/>
      <ins:fingering name="Sharp" comment="Use in combination with E4. G4 is sharp" keysDown="T,L-1,RT-2"/>
    </ins:note>
    <ins:note name="A4">
      <ins:fingering name="Basic" comment="Basic. Try using RH-1,2,3 in different conbinations for better intonation and tone" keysDown="L-A"/>
      <ins:fingering name="Full" comment="Fuller sound without sounding airy" keysDown="L-A,R-2,R-3,R-F"/>
      <ins:fingering name="Flat" comment="Flatter" keysDown="L-A,L-2,L-3,R-2,R-3,R-F"/>
    </ins:note>
    <ins:note name="A#4 / Bb4">
      <ins:fingering name="Basic" comment="Basic. Try different RH combinations for better intonation and tone." keysDown="R,L-A"/>
      <ins:fingering name="Trill-A4" comment="Trill fingering with A4. Try different RH combinations for better intonation and tone." keysDown="L-A,RT-2"/>
      <ins:fingering name="Alt1" comment="Better in tune and clearer than basic fingering" keysDown="R,L-A,L-3,R-1,R-3,R-F"/>
      <ins:fingering name="Alt2" comment="Better in tune and clearer than basic fingering" keysDown="R,L-A,L-3,L-F,R-1,R-3"/>
      <ins:fingering name="Alt3" comment="Good intonation and smooth transitions with other notes" keysDown="R,L-A,L-1,L-2,L-3,R-2,R-3"/>
      <ins:fingering name="Alt4" comment="Fuller sound; in tune; less awkward" keysDown="R,L-A,L-2,L-3,R-2,R-3,R-F"/>
      <ins:fingering name="Alt5" comment="In tune and fuller, less airy sound" keysDown="R,L-A,L-3,R-3,R-F"/>
    </ins:note>

    <!-- Clarion Register -->
    <ins:note name="-- Clarion Register --">
        <ins:fingering name="B4-C6" comment="" />
    </ins:note>
    
    <ins:note name="B4 / Cb5">
      <ins:fingering name="Left" comment="Use in combination with fingerings using right little finger or no little fingers" keysDown="R,T,L-1,L-2,L-3,L-E,R-1,R-2,R-3"/>
      <ins:fingering name="Right" comment="Use in combination with fingerings using left little finger or no little fingers" keysDown="R,T,L-1,L-2,L-3,R-1,R-2,R-3,R-E"/>
